package cherokees.jpa.entities.organisation;

@Entity
public class TrainingChoice {

		@Id
		@Autogenerated
		Integer id;
		
		
		public TrainingChoice() {
			super();
		}


		public TrainingChoice(Integer id) {
			super();
			this.id = id;
		}


		public Integer getId() {
			return id;
		}


		public void setId(Integer id) {
			this.id = id;
		}
}
